### ISSUE TITLE
Fix opacity of invisible canvas box

### ISSUE THREAD

**Issue by yhahn** [mapbox/maki#201]
> Dane Springmeyer: maki has this rect that is meant to be invisible, but uses opacity:0.5

- Fix
- Add test

**Comment by ajashton** [comment]
https://github.com/mapbox/maki/pull/202

Still todo: add test

**Comment by nebulon42** [comment]
Could you please explain to a beginner in SVG map icons the rationales behind these canvas boxes? I'm not sure why they are needed. Thanks.

**Comment by ajashton** [comment]
They are a workaround for Mapnik and other programs/libraries that ignore the width and height properties of the `<svg>` element and instead determine width and height of the image automatically by a bounding box of the shapes within the image. I think the history behind programs doing this has to do with the prevalence of SVGs with incorrectly specified dimensions and automatic detection providing more expected results for users much of the time.

**Comment by nebulon42** [comment]
Thanks for elaborating. I did a test run with a SVG containing a rather flat shape inside a 16x16 canvas with/without the canvas box, but didn't notice any differences in positioning in Tilemill.

I'm asking because at [gravitystorm/openstreetmap-carto](https://github.com/gravitystorm/openstreetmap-carto) we are currently in the process of replacing PNGs with SVGs and so far I didn't notice the need for such canvas boxes.

**Comment by ajashton** [comment]
This won't effect icons at their default sizes, this will only matter if you are changing the marker-width or marker-heightt. Say you have a 16x16px SVG containing just a 8x8px square. If you set `marker-width: 32` it would be just the 8x8px square that gets scaled to 32x32px, not the 16x16 icon as a whole.

**Comment by nebulon42** [comment]
Now I understand. I guess I have noticed this effect already, but did not know why it occured. Thanks for explaining.

**Comment by ajashton** [comment]
Done in #204
