### ISSUE TITLE
scooter/motorbike icon

### ISSUE THREAD

**Issue by sbma44** [mapbox/maki#263]
maki 3 dropped `scooter` and I'm left unsure what to use for the Factual POI category `Motorcycles, Mopeds and Scooters` in our POI => maki mapping in the geocoder. A general motorized bike icon would be useful to have.

refs https://github.com/mapbox/sirius-ios/issues/611

**Comment by natslaughter** [comment]
@samanpwbb 
Pushed draft scooter icons in the 'new-icons' branch.
Let me know what you think.

cc @sbma44

**Comment by aparlato** [comment]
Changed the 11px, and as per discussion with @natslaughter , slightly increased the visibility of the back wheel on the 15px, but otherwise largely left the previous version alone.

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21438330/565d86be-c856-11e6-9fa3-877bbc955a09.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21438333/5d23adac-c856-11e6-9738-40171d0b9eb4.png)


**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21438182/c289f314-c855-11e6-99b4-fe04bd578efc.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21438191/c9be5e7c-c855-11e6-8ca1-7cd46fd30934.png)

**Comment by natslaughter** [comment]
@aparlato 
Looks great!
It seems that now the two icons might be slightly too different, especially in the seat area. 
Do you think we should pick one direction and try to make the other icon more similar?

**Comment by aparlato** [comment]
@natslaughter 
Modified the seats to be more similar. Below I've posted two versions, each with a different seat. Conflicted about which seat to choose as I prefer the one with the flatter front, but it may be less clear in the 11px.

Both options below for opinions: 

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21438974/92615e4e-c859-11e6-8deb-cc21e56673ad.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21438985/99cb87b8-c859-11e6-8fe0-cbac98701857.png)

**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21438991/a34b7690-c859-11e6-9a01-6a5e908f4e00.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21439000/ab38af9e-c859-11e6-88f2-5fb0ff568d16.png)
____
**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21439015/baf92864-c859-11e6-9144-49cc8be783f2.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21439023/c242f208-c859-11e6-801a-9085b57927ee.png)



**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21439136/4bf4ff5a-c85a-11e6-91c3-c88118076f27.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21439142/52d0575c-c85a-11e6-97a8-3abaabeb7dc1.png)

**Comment by nickidlugash** [comment]
This was done.
