### ISSUE TITLE
grill icon

### ISSUE THREAD

**Issue by bhousel** [mapbox/maki#276]
Need a "Grill" icon for a Very Important Project. 🍖 

No strong opinion here on charcoal / gas, they both have their advantages and disadvantages.

per @gundersen

**Comment by natslaughter** [comment]
@bhousel 
I'll get started on the grill icon request this week. 
What's your timeline?

**Comment by bhousel** [comment]
@natslaughter Lets try to get this done by Labor Day weekend

**Comment by gundersen** [comment]
> Labor Day weekend

And miss the entire 2016 grilling season?

**Comment by bhousel** [comment]
ok ok.. Guess this means I'll have to upgrade iD to Maki2 by 4th of July.. 😄 🎆 🇺🇸

**Comment by natslaughter** [comment]
@samanpwbb @bhousel 
Just added first drafts of the grill icons.

**Comment by aparlato** [comment]
I left the 15px as @natslaughter had it because I think it's working very well, but I changed the 11px to look more like the 15px.

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21430802/b73717f8-c832-11e6-800d-5a884895a51e.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21430808/bdb188ca-c832-11e6-8a1d-0f76e7312783.png)

OR a slight variation with a deeper rounded section (although I prefer the above ^)

![image](https://cloud.githubusercontent.com/assets/15698320/21430881/0cc276c2-c833-11e6-9d73-cb12e282cdf3.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21430882/13d0ff92-c833-11e6-8a3b-7c4db0eaf425.png)




**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21430756/84c0d2e6-c832-11e6-9a71-fd5227636ebd.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21430767/8e5fbb3c-c832-11e6-9afd-a662eb4ef2f2.png)

**Comment by natslaughter** [comment]
@aparlato 
The 11-pixel icon is looking good. I have a couple of issues that if the pixel space allows, would be nice to change.

11-pixel
- The legs are more spread out compared to the 15-pixel icon. Curious to see if bringing the legs in would look better.
- I'm also curious to see what a thicker wheel outline would look like. Currently, the outline is thinner than the legs, and am wondering if this should be the opposite: Wheel thicker, Legs thinner.

**Comment by aparlato** [comment]
@natslaughter good suggestions! I think this looks way better with the steeper angle, thin legs, and thick wheel.

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21436518/f3a2b0ca-c84c-11e6-8968-8a8ff50d3abc.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21436525/fb2a0c9e-c84c-11e6-954e-b6602ae5cfef.png)

with the 15px
![image](https://cloud.githubusercontent.com/assets/15698320/21436518/f3a2b0ca-c84c-11e6-8968-8a8ff50d3abc.png) ![image](https://cloud.githubusercontent.com/assets/15698320/21436536/0b621a5c-c84d-11e6-83f8-cd979ed1e38e.png)

**Comment by aparlato** [comment]
This was done.
