### ISSUE TITLE
home icon

### ISSUE THREAD

**Issue by YunjieLi** [mapbox/maki#281]
I'm surprised there are no home/house/apartment icon in the maki?

We (I) should make one!

**Comment by samanpwbb** [comment]
Hi @YunjieLi! Would love to have you contribute to maki. Check out the guidelines: https://www.mapbox.com/maki-icons/guidelines/

Ping me in chat if you want to talk more about this.

**Comment by natslaughter** [comment]
@nickidlugash 
@YunjieLi started this home icon several months ago, and wanted to post progress to the ticket for your feedback:

11-pixel
![screen shot 2016-12-20 at 1 06 47 pm](https://cloud.githubusercontent.com/assets/16616543/21362198/58c24a36-c6b5-11e6-8450-7f23ff562e97.png)

15-pixel
![screen shot 2016-12-20 at 1 06 55 pm](https://cloud.githubusercontent.com/assets/16616543/21362210/5f4a7522-c6b5-11e6-9d22-a62514fafd5a.png)

**Comment by aparlato** [comment]
I'm torn about which house is working best. The house, at dead center on the artboard, is put in a situation where the door and window widths end up looking either a little too narrow or a little too wide when they are pixel aligned. I'm posting a list of a number of variations at scale as well as my personal preference at this point.

1) ![image](https://cloud.githubusercontent.com/assets/15698320/21428647/226efec8-c829-11e6-9566-ecf1de85613a.png)
too little detail

2) ![image](https://cloud.githubusercontent.com/assets/15698320/21428653/2e0df0fe-c829-11e6-9673-e8c2533867e3.png)
this one is nice, but the windows get too close to the edge
3) ![image](https://cloud.githubusercontent.com/assets/15698320/21428661/387c8654-c829-11e6-8359-3ae2cfbbd7f4.png)
my personal favorite, however the door makes a big jump in size

4) ![image](https://cloud.githubusercontent.com/assets/15698320/21428689/54f9bf5e-c829-11e6-8e0a-acf449dec686.png)
this house looks too skeptical and kind of mad

5) ![image](https://cloud.githubusercontent.com/assets/15698320/21428702/5dc5ae90-c829-11e6-8da1-d2fbe5ecfada.png)
windows feel bunched together

6) ![image](https://cloud.githubusercontent.com/assets/15698320/21428713/6658f5e4-c829-11e6-8fc2-a795d40a8476.png)
although the windows are in the same spot as 2, without the door it bothers me less
____
Here's number 3 from above in more detail. I think this option is working best because it has some detail, but the lack of windows actually helps to differentiate it from city, town, village, and building.
**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21428828/fba31634-c829-11e6-9fd3-cbc659976716.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21428849/1f32608c-c82a-11e6-93ff-5ad9eb59f0f7.png)

**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21428823/f3a793ce-c829-11e6-882f-6d78078a545b.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21428855/2458fbca-c82a-11e6-93ab-e11d9bd52f1b.png)

**Comment by aparlato** [comment]
Thoughts on this approach?

**11:** 
![image](https://cloud.githubusercontent.com/assets/15698320/21438515/71dbbdf6-c857-11e6-8662-390153df0ada.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21438523/7e2cbed4-c857-11e6-835f-c743b7861ab4.png)

**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21438531/876377a4-c857-11e6-8fa3-2b5a4effa3e6.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21438535/8fb9a0c2-c857-11e6-9a51-ee1ce2b8bc97.png)

**Comment by aparlato** [comment]
This was done.
