### ISSUE TITLE
logging icon

### ISSUE THREAD

**Issue by aparlato** [mapbox/maki#309]
For id-support from #270 

[Logging on taginfo](http://taginfo.openstreetmap.org/tags/landuse=logging)

[reference to Maki 1 icon for logging](https://github.com/mapbox/maki/blob/15464764a01d03e9b62a6c601c0f28564b0d5fb9/src/logging-24.svg)

icon for landuse:logging

cc @nickidlugash

**Comment by aparlato** [comment]
**First draft**

I tried other approaches that looked more like a regular saw, but it started to look too much like a key, so for now I went back to using a chainsaw symbol which I think is working fairly well.

**11:** 
![image](https://cloud.githubusercontent.com/assets/15698320/21162919/bbcc4cd8-c144-11e6-96df-58e9db1b803a.png)

**15:** 
![image](https://cloud.githubusercontent.com/assets/15698320/21162927/cbceee92-c144-11e6-80e3-4a6f0b991407.png)

**Comment by natslaughter** [comment]
@aparlato 
Looks good!
The handle geometry needs a bit of smoothing:

![screen shot 2016-12-14 at 10 08 37 am](https://cloud.githubusercontent.com/assets/16616543/21187313/75fdb8a8-c1e5-11e6-82cc-e45bd3a23619.png)  
15 pixel  

![screen shot 2016-12-14 at 10 09 21 am](https://cloud.githubusercontent.com/assets/16616543/21187322/7d4515a2-c1e5-11e6-9252-efdc1c06c5aa.png)  
11 pixel

**Comment by nickidlugash** [comment]
A couple of suggestions for constructing geometries:

- Make sure that where lines connect to curves, the lines are tangent to the curve

![tangent](https://cloud.githubusercontent.com/assets/5607844/21193354/04593988-c1fa-11e6-8ab5-1a82c48f9abf.gif)

- Check your paths to make sure there are no extraneous nodes.

- Where possible, I would make the geometry more regular. So for example, for both handles, you may want to explore adjusting the shape of the curved area so that the width of the handle line stays consistent between the straight part and the curved part.

**Comment by aparlato** [comment]
**Draft 2**

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21204821/0071317c-c20e-11e6-899a-3d88843d83f7.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21204847/1764d604-c20e-11e6-95e2-da391bbc5524.png)


**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21204828/060b8ba0-c20e-11e6-9558-724880a502cc.png)

below: I circled a slightly wonky part that no matter how many times I correct and export it seems to appear this way when I open the svg back up. I tried other big changes as a test and it's not reverting to an old version based on that. Not sure what's going on there.
![image](https://cloud.githubusercontent.com/assets/15698320/21204881/439466f4-c20e-11e6-9cda-5c47943f5cc5.png)

**Comment by natslaughter** [comment]
@aparlato 

I've noticed that Illustrator sometimes has a difficult time working at this "single pixel" scale, however, I have found that setting up new documents with a profile of the default `custom` value (instead of changing it to `web` or `basic rgb`) helps with this. Sometimes this doesn't help and I don't know why.
I've also noticed that Illustrator has some rendering issues at this scale as well, so your geometry could be fine, but Illustrator just isn't rendering it correctly. Sometimes it helps to open your file up in another vector drawing application like Inkscape just to double check. 

That said, I noticed that there is another issue with this handle element. I offset the bottom curve .5 pixels, and noticed that it doesn't match up with the top curve: they are on different arcs. Fixing this could also help with the handle's "wonkiness." 

![screen shot 2016-12-15 at 11 46 48 am](https://cloud.githubusercontent.com/assets/16616543/21233326/be023a48-c2bc-11e6-9f07-8f33398f91ca.png)

**Comment by natslaughter** [comment]
@aparlato 
Also, the 11 pixel has a curved end and the 15 pixel has a flat end. I think the ends should both be curved.

**Comment by aparlato** [comment]
**Draft 3**

_quick note:_ I notice in the larger screenshots here it looks like a tiny tiny white dot on the path, but it's just an anchor, so it should be smooth.

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21235061/18609696-c2aa-11e6-98a6-6c7d539e06b5.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21235077/26a67c48-c2aa-11e6-8056-e7d8afbeac50.png)



**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21235319/1ff1792e-c2ab-11e6-8e52-947bc7f7e586.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21235372/50397258-c2ab-11e6-9ee9-59a5c9124462.png)

**Comment by natslaughter** [comment]
@aparlato 
The white dot on the edge you're noticing is just Illustrator's rendering, not your geometry. It's annoying at times.

**Comment by aparlato** [comment]
**Draft 4**

I tried to make the handles round down more and made the lower (body) sections of the chainsaws more similar to each other. I made the saw blades more friendly although the 15 size is still a little chunky because of the length of
Also, if anyone has a solution, Illustrator sometimes changes the shape of objects I'm working on a good deal when I use pathfinder->unite and I have to go manually fix it. Not sure why this is happening.

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21245696/fef0050a-c2d8-11e6-8bff-d75472c15f37.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21245700/05358a20-c2d9-11e6-8fbe-7aaedc03f9fc.png)

**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21246094/69928c1e-c2db-11e6-838d-c9f650b8f4e4.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21246100/718fc242-c2db-11e6-87cf-5f7368550773.png)

OR **with a slightly different handle** that makes it just a _little_ less clear at scale.

**11:** 
![image](https://cloud.githubusercontent.com/assets/15698320/21246292/a3df2674-c2dc-11e6-8954-b5970c447275.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21246296/ac2f7f36-c2dc-11e6-979f-ddfde62f49e3.png)
**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21246306/b8c0c6b0-c2dc-11e6-9c24-5accee40381d.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21246317/c5135798-c2dc-11e6-9b8a-46fa739654eb.png)

**Comment by natslaughter** [comment]
per discussion with @aparlato

Regarding the 15-pixel icon:
![screen shot 2016-12-19 at 12 23 41 pm](https://cloud.githubusercontent.com/assets/16616543/21322205/0375318a-c5e6-11e6-9209-a6e943aee1e6.png)

**Comment by aparlato** [comment]
**15px Fixed**

![image](https://cloud.githubusercontent.com/assets/15698320/21322211/0d7a8eaa-c5e6-11e6-8914-5eec43b00c93.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21322233/2d040c38-c5e6-11e6-8e8a-aefc9d95c0da.png)
pixel-preview :+1::
![image](https://cloud.githubusercontent.com/assets/15698320/21322245/3b5b1ed4-c5e6-11e6-86f0-a5bb2f34d209.png)

**Comment by aparlato** [comment]
new and improved **with handle**

The only way to give a gap in the 11px was to not fully close the handle, but I feel like this solution makes sense still. 

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21328656/0c6d8b8a-c603-11e6-9834-5554f9b9eb8b.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21328662/13158a82-c603-11e6-9032-946bb757fee6.png)



**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21328666/190a1df4-c603-11e6-993e-66bd049e2f31.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21328685/225d4d72-c603-11e6-930e-be9f5fac5d15.png)

**Comment by aparlato** [comment]
This was done.
