### ISSUE TITLE
Natural / Landcover icon

### ISSUE THREAD

**Issue by bhousel** [mapbox/maki#328]
For id-support from #270 

The landuse icon #319 looks great!

As an additional request:
There are 2 other bunches of tags in OSM for "natural" / "landcover" which we could use an icon for.
see: https://github.com/openstreetmap/iD/issues/2843#issuecomment-166346626

The icon for this would be just like the landuse icon, and should probably re-use elements of that icon, but this would only include natural features.

[Natural on taginfo](http://taginfo.openstreetmap.org/keys/natural#overview)
[Landcover on taginfo](http://taginfo.openstreetmap.org/keys/landcover#overview)

**Comment by aparlato** [comment]
**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21399600/48509f5c-c77a-11e6-8999-50da5222dfe6.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21399624/4e9554ca-c77a-11e6-9894-6e5b756e8a17.png)

**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21399635/5a0c0cfe-c77a-11e6-99db-ecec663dc426.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21399642/5f59342a-c77a-11e6-8a26-57ee25bdc5a9.png)

____
vs

landuse

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21399682/856b8e2e-c77a-11e6-9368-a769cdd391c9.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21399687/8ac19008-c77a-11e6-830d-cde6738a5398.png)



**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21399692/91ddb510-c77a-11e6-8896-d0d61f355b3d.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21399696/99716182-c77a-11e6-8d9d-020d2ecadfa5.png)


cc @nickidlugash @natslaughter

**Comment by natslaughter** [comment]
@aparlato 
The new building looks great!

landcover icons:
- The 'grass' element seems too unique compared to the other two elements. It might help if the top s were thicker and had rounded ends, and also the base needs a bit of finessing. 

landuse icons:
the 15-pixel icon has a central void that doesn't allow the three elements to be a singular element. Try decreasing this space: maybe pull the industrial building inwards.

**Comment by aparlato** [comment]
**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21402210/88ee4360-c785-11e6-9de4-febdde9f9fa8.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21402228/a1df33d4-c785-11e6-9b6a-655054422cf6.png)
I think it in this one the grass is looking less smooth due to rendering, see below.
![image](https://cloud.githubusercontent.com/assets/15698320/21402239/ab71e770-c785-11e6-9f77-5d29775e9ed2.png)



**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21402283/cfba1594-c785-11e6-8ec1-b1fb1b216b94.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21402291/d6df4ace-c785-11e6-8907-598ed89c1abc.png)
____

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21402308/e55b8766-c785-11e6-8fb4-5d7cc9948442.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21402315/ee14abbc-c785-11e6-953d-15373700ad46.png)



**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21402321/f2a51d42-c785-11e6-8583-e2a5e19c4ae3.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21402329/f9694e32-c785-11e6-9b23-e0a5cf1e0382.png)

**Comment by aparlato** [comment]
Ideally I'd like to round out the ends of the plant, but in the 11px it would make the plant very unclear. Do you all think this solution looks good?

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21406225/72975ce2-c798-11e6-8643-e26797b79470.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21406229/7d0cc4a0-c798-11e6-952c-d3adeb98f362.png)

**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21406250/9695ae46-c798-11e6-801d-87be4c509248.png)
tiny rendering issue in the middle leaf of the plant, but in reality it's smooth.
![image](https://cloud.githubusercontent.com/assets/15698320/21406238/8e46e2c8-c798-11e6-8624-b169b4047a8d.png)

**Comment by aparlato** [comment]
Tighter arrangement replacing grass with flower.

**11:**
![image](https://cloud.githubusercontent.com/assets/15698320/21407843/8eaff414-c79f-11e6-8f34-ebd5a964d9cd.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21407851/9707b408-c79f-11e6-90e3-4a00a233748a.png)

**15:**
![image](https://cloud.githubusercontent.com/assets/15698320/21407857/a12d583e-c79f-11e6-83c0-cdeb81008503.png)
![image](https://cloud.githubusercontent.com/assets/15698320/21407863/aa2b7286-c79f-11e6-8334-777c2cdc4592.png)

**Comment by aparlato** [comment]
This is done.
