### ISSUE TITLE
Anchor icon blurry

### ISSUE THREAD

**Issue by pnorman** [mapbox/maki#364]
I noticed on the website that the middle of the anchor icon was blurry compared to all the other icons

![image](https://cloud.githubusercontent.com/assets/1190866/22007234/03919f90-dc26-11e6-8129-3dcee1441d36.png)

![image](https://cloud.githubusercontent.com/assets/1190866/22007231/fbdc74aa-dc25-11e6-8c90-5c2f27159c0a.png)

The circle also seems odd to me, coming up closer to the eye than I'd consider normal, and being a full half-circle which is also [relatively uncommon](https://www.google.ca/search?q=anchor+icon&tbm=isch), but those are design choices, not technical requirements.

**Comment by natslaughter** [comment]
@pnorman Thanks for your interest in Maki!

> the middle of the anchor icon was blurry  

Are you referring to the vertical stem that connects the eye circle and the bottom half circle?

**Comment by pnorman** [comment]
> Are you referring to the vertical stem that connects the eye circle and the bottom half circle?

Yes

**Comment by natslaughter** [comment]
@pnorman 
The middle stem (vertical line) is somewhat blurry due to the line width being 2 pixels, and on-center within the confines of an odd-number width dimension (11-pixel and 15-pixel). 50% of this line fills the center pixel column, and the remaining 50% extends into the adjacent columns (25% to the left and 25% to the right), causing these pixels to render a 25% black (grey) color value. We chose to keep the line 2 pixels in width and be somewhat blurry instead of increasing the line width to 3 pixels; thus having to change all line work to 3 pixels. This would create other issues; for example the negative space inside the anchor's eye would be significantly smaller and wouldn't read at 100% scale. 
Hope this answers your question, and thanks again for your interest in Maki!
