### ISSUE TITLE
refine cricket icons

### ISSUE THREAD

**Issue by natslaughter** [mapbox/maki#426]
purpose of this ticket is to take the existing cricket icons, which incorporate the human figure, and create new cricket icons with no human. 

#### existing icons

![screen shot 2018-04-17 at 5 23 34 pm](https://user-images.githubusercontent.com/16616543/38899313-775ead5e-4265-11e8-853b-8e037744eaf2.png)

#### possible new icon concept

cricket bat

![image](https://user-images.githubusercontent.com/16616543/38899308-733c2f12-4265-11e8-8700-d46ca8acdd22.png)

**Comment by rasagy** [comment]
I took the cricket bat concept forward: Unlike the other sport icons with a bat/racket, I flipped this to better match the common stance in cricket (bat is held with the handle in the top direction). I also tried to add negative space in two sections — near the join of the handle with the hitting surface, and the bottom part (which is sometimes branded or taped for support):

<img width="37" alt="screenshot 2018-06-22 19 12 15" src="https://user-images.githubusercontent.com/1117531/41779970-017f880e-7651-11e8-808c-0aa18b22d188.png">

Example of the join and the band near the bottom edge: ![Image from https://www.dreamstime.com/](https://thumbs.dreamstime.com/z/cricket-bat-ball-26570619.jpg)

I’m realizing that the negative space near the handle isn’t working very well with the 11px icon. Here’s the above icon along with another attempt with a deeper stroke below it:

<img width="17" alt="screenshot 2018-06-22 19 12 06" src="https://user-images.githubusercontent.com/1117531/41780001-1928eb9e-7651-11e8-8b52-6ffb21e2dfd2.png">

<img width="85" alt="screenshot 2018-06-22 19 20 32" src="https://user-images.githubusercontent.com/1117531/41780078-5a1b3c24-7651-11e8-9e2e-e021f61f6e63.png">

@natslaughter Would you recommend ditching the negative spaces since they might not add a lot to the shape to make it recognizable/distinct?

**Comment by rasagy** [comment]
Closing this — we decided to skip using a separate icon for cricket for this update.
