### ISSUE TITLE
seafood restaurant icon

### ISSUE THREAD

**Issue by natslaughter** [mapbox/maki#430]
### seafood restaurant icon

**use case**
For places that sell seafood

**tagging information**
Maki field = { cuisine: 'seafood' }
[OSM tag info](https://taginfo.openstreetmap.org/search?q=seafood#values)

**possible symbol**
lobster

![image](https://user-images.githubusercontent.com/16616543/38900353-2c65ef7a-4269-11e8-8519-2ab34d0299eb.png)

**Comment by natslaughter** [comment]
going with a lobster for the symbol concept. this _might_ be a stretch and will revert to different silhouette. 

<img width="342" alt="screen shot 2018-05-10 at 11 08 23 am" src="https://user-images.githubusercontent.com/16616543/39877012-bda06386-5442-11e8-8f14-96791ec2cc4b.png">

**next steps**
- [ ] icon design refinement
- [ ] test icon on maps
- [ ] geometric cleaning & svg file preparation

**Comment by natslaughter** [comment]
[good research here](https://www.pressherald.com/2018/02/08/lobster-emoji-stumbles-probably-for-want-of-2-more-legs/)

**Comment by natslaughter** [comment]
Although using a lobster as the symbol concept would be ideal, it is proving to be a difficult drawing exercise at Maki scale. Below are refined lobster symbols, in addition to a fish symbol. Our existing aquarium icon uses a fish, however I think this fish is different enough to be used. 

<img width="595" alt="screen shot 2018-07-09 at 1 30 23 pm" src="https://user-images.githubusercontent.com/16616543/42466465-03191930-837d-11e8-8550-23a63db47132.png">

**Comment by natslaughter** [comment]
@samanpwbb suggests a crab

**Comment by aparlato** [comment]
@natslaughter I agree that a crab would likely work well since it does have a fairly distinctive shape.
<img width="30px" src="https://user-images.githubusercontent.com/15698320/42479562-5c81913a-838e-11e8-9466-a36836564648.png"/>
I did a really quick rendition of an 11px crab as a test which I think visually reads well.

That said, I think lobster b is very nice, but I do sense that it would feel ambiguous without context. The fish icons all together feel too ambiguous to me and making them more fish-like would be confusing with the aquarium.

**Comment by tristen** [comment]
Closing. This exists.

**Comment by tristen** [comment]
https://github.com/mapbox/maki/pull/443
