### ISSUE TITLE
re-draw the school icon

### ISSUE THREAD

**Issue by natslaughter** [mapbox/maki#434]
The current `school` icon is something I am more embarrassed by than proud of, and I would like to remedy that. The icons are prevalent on Mapbox core style maps, and should be a great icon. 

Here are the current school icons: 
<img width="423" alt="screen shot 2018-05-31 at 9 54 42 am" src="https://user-images.githubusercontent.com/16616543/40786283-b39b2340-64b8-11e8-8a85-c306ca93435f.png">
<img width="374" alt="screen shot 2018-05-31 at 9 54 50 am" src="https://user-images.githubusercontent.com/16616543/40786288-b55b90d4-64b8-11e8-910d-61e85087ca83.png">

**next steps**
- [ ] select a new symbol concept
- [ ] icon design refinement
- [ ] test icon on maps
- [ ] geometric cleaning & svg file preparation

**Comment by bhousel** [comment]
Yeah this one is tricky!  

FWIW, I think the icon looks ok as-is.  But in iD we are using it for a lot of different kinds of school POIs, from nursery school up to high school, and it's difficult to make an icon that conceptually covers all these usecases  (I've always thought it looks kind of silly on both nursery or high school - they're not really measuring things with rulers).  

We may also have some presets that use this icon in a totally odd way (music school / dance school / driving school) but in those cases I think we should just pick a different icon.

**Comment by eschow** [comment]
I agree with @natslaughter that the icon can be revisited but also agree with @bhousel that it'll be super tricky. While I don't think the icon accurately reflects what I think of when I think "school," reading the different use cases @bhousel described above are interesting ones to dig into to understand _how_ the icon is being used and _why_. Excited to follow along!

**Comment by MwithHook** [comment]
So this is pretty unusual for a school icon. [Take a look at common ones](https://www.google.com/search?q=school+icon&rlz=1C1ASRM_enUS733US733&sxsrf=ALeKk03q5w25fXLL9B6VZr87tLfPFfGkHw:1585270527282&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjm1Jr1uLnoAhVRgK0KHaZ4BB8Q_AUoAXoECA0QAw&biw=2133&bih=1028). We should really have a building with a clock/flag. Might not be typical realistically anymore, but people recognize it instantly, it's by far the most popular symbolic representation of a school.

**Comment by SDNTV** [comment]
Please redraw the school icon!  I suggest an APPLE.  All Americans associate an apple with teachers/schools.  It's simple and will be discernible no matter its sizing.

**Comment by todrobbins** [comment]
The [temaki](https://ideditor.github.io/temaki/docs/#icon-temaki-school) version is clearer, but a building is probably better:

![](https://raw.githubusercontent.com/ideditor/temaki/master/icons/school.svg)

**Comment by Udobnyj** [comment]
I did some work here.
Like I said at the grooming meeting. First, my idea was a globe, but I forgot that we already have one. 😅 So I started thinking that the school is the most connected with pens, rulers, books, and backpacks. 

If you want to look closer at all options, here is the [Figma link](https://www.figma.com/file/sW5W8xFa7RzsbgU6JTNwwJ/Maki-WIP?node-id=523%3A1343)

I chose two options:
1. Graphically updated our classic icon ![school.svg](https://images.zenhubusercontent.com/61dc302270b3029c9827fc13/9c919622-851a-4aef-a47f-d86c6cf3abda) [Studio link](https://api.mapbox.com/styles/v1/udobnyi/cl3cwfw7g000314tmmaipnyfr.html?title=view&access_token=pk.eyJ1IjoidWRvYm55aSIsImEiOiJja3liZGU0NzMwZTlhMnBvOHFuOWxlNmYxIn0.mhFm05xmSMi6w28_1fvxVg&zoomwheel=true&fresh=true#15.86/37.722062/-122.406524)

![Screen Shot 2022-05-19 at 12.50 1.png](https://images.zenhubusercontent.com/61dc302270b3029c9827fc13/32521019-a9c5-4817-8337-479c27d79e5a)

2. Backpack icon ![school.svg](https://images.zenhubusercontent.com/61dc302270b3029c9827fc13/880c95fc-74bd-4fe7-8903-1b4a268d7e3b) [Studio link](https://api.mapbox.com/styles/v1/udobnyi/cl3csg0gb000i15mqueee151y.html?title=view&access_token=pk.eyJ1IjoidWRvYm55aSIsImEiOiJja3liZGU0NzMwZTlhMnBvOHFuOWxlNmYxIn0.mhFm05xmSMi6w28_1fvxVg&zoomwheel=true&fresh=true#15.81/37.724024/-122.406226)

![Screen Shot 2022-05-19 at 13.55 1.png](https://images.zenhubusercontent.com/61dc302270b3029c9827fc13/2c52a596-349d-4a60-9307-f5a001abe62d)

@tjukanovt @willymaps What do you think?

**Comment by willymaps** [comment]
> Graphically updated our classic icon

@Udobnyj I really like this one! The ruler might be too large in comparison to the pencil, but feel free to open a PR.

🌶️  – I wonder if we really need this icon? [College](https://github.com/mapbox/maki/blob/main/icons/college.svg) or [library](https://github.com/mapbox/maki/blob/main/icons/library.svg) seem more consistent with other school icons and differentiating between levels of education in our map styles might not be that important?

**Comment by tayalav** [comment]
Maybe you could try [globe](https://thenounproject.com/icon/globe-4837463/) for school?
![Screenshot 2022-05-23 at 18.58.58.png](https://images.zenhubusercontent.com/60ed6de80f59660642398580/8b570430-0cef-4d78-a4da-2cc2d503f39a)

**Comment by Udobnyj** [comment]
@willymaps Thank you for the comment. I'll change the ruler a bit.
Answering your question: I'm not sure about it ¯\_(ツ)_/¯. For me, the Library and College icons are too specific. 
Maybe we can use the college icon for schools, but for me, the school is closer to the Kindergarten (as far as I know, we have no Kindergarten icon too). 

@tayalav, hey! I wrote about it in my comment. Unfortunately, we already have a globe icon in Maki, which isn't for schools.

**Comment by Udobnyj** [comment]
@willymaps 

Did four options

![school.svg](https://images.zenhubusercontent.com/61dc302270b3029c9827fc13/210545c3-c033-435d-bda1-f50754c93c1d)
![Screen Shot 2022-05-24 at 11.19.38.png](https://images.zenhubusercontent.com/61dc302270b3029c9827fc13/1119d689-ce46-4ac7-ae6e-20ea4cfa16aa)

![school.svg](https://images.zenhubusercontent.com/61dc302270b3029c9827fc13/3b3e8c40-6ca0-4124-abea-46eb8838595e)
![Screen Shot 2022-05-24 at 11.20.02.png](https://images.zenhubusercontent.com/61dc302270b3029c9827fc13/8983d65c-f419-41d9-8f9b-9bf9c7bfd605)

![school.svg](https://images.zenhubusercontent.com/61dc302270b3029c9827fc13/37e9b726-312d-457a-9ef1-bf999b2d2d22)
![Screen Shot 2022-05-24 at 11.21.37.png](https://images.zenhubusercontent.com/61dc302270b3029c9827fc13/467eb4b5-30d9-40cb-8a91-cb0494bbb12f)

![school.svg](https://images.zenhubusercontent.com/61dc302270b3029c9827fc13/0dedf349-8d16-4fee-af2d-346894e2b71a)
![Screen Shot 2022-05-24 at 11.26.03.png](https://images.zenhubusercontent.com/61dc302270b3029c9827fc13/91ba833a-7eff-46cd-952b-28070b844be7)

**Comment by tayalav** [comment]
The main idea of this task is to rethink the symbol concept. I agree with @natslaughter that `pencil and ruler` is hard to distinguish on the map ngl

**Comment by Udobnyj** [comment]
I figured out that globe icon that we already have ![globe](https://user-images.githubusercontent.com/5434742/171410943-ee4329e8-f880-4943-afc2-03a83d3ae4ff.svg) is not really useful, because it's using `to represent map & globe stores, cartographic service companies, etc.` which I think is too specific. But, we can easily take it and use it for schools.

I checked this information with Nikolay Lebedev, and everything turned out exactly like that.
We use this icon only 32 times worldwide.
![image (1)](https://user-images.githubusercontent.com/5434742/171423113-79b24695-0b34-4c80-8d01-5cb0ed33154a.png)

Anyway, I checked another map's services. And here is what I've got.
<img width="2749" alt="Frame 1" src="https://user-images.githubusercontent.com/5434742/171430475-8aa1016e-5d65-49f0-b72c-4e5174775a11.png">

Baidu, Weibo, and Naver are using unique icons for school.
Google and Yandex use the one for school and university.

I think we can go both ways. If we need this special icon, we can take the globe one.
But we can just cut it off and do like Google and Yandex.
After all research, I think the best way will be to just kut it off, but I wanted to hear your thought once again.
@willymaps @tayalav

**Comment by Udobnyj** [comment]
@tayalav Yeah. I didn't know that we were using one icon for `school` and `kindergartens`.
I think it's an excellent point to separate this icon. Because one icon for universities and schools it's ok, but kindergartens are not suitable here. The university icon is different from the kindergarten icon on all services where I checked this.

So let's do it! Let's start using the globe icon for schools and kindergartens.

**Comment by Udobnyj** [comment]
Hey @melanieimfeld! Good thoughts! I didn't think about the triangle ruler, and it's really working better.

But do you think "pencil and ruler" are working for kindergartens too?
And I wanted to ask about the globe. Does it seem that it doesn't work as a metaphor for primary education? As if we are talking about geography lessons where children learn about the world, about other countries.

**Comment by Udobnyj** [comment]
After the survey, it became clear that the globe metaphor is not clear to anyone. So the majority voted for the pencil and ruler.
![Screen Shot 2022-06-20 at 12.58.14.png](https://images.zenhubusercontent.com/61dc302270b3029c9827fc13/142ce94d-32b3-46e1-9a34-5fba6187b30d)

But there was also a second option — a pencil and an apple, which I also liked.
So, we already have the usual pencil and ruler icon (up there). 
I tried @melanieimfeld option w a triangle ruler.

[MAP LINK](https://api.mapbox.com/styles/v1/udobnyi/cl4o7bpzr005l14pfxpi6ap8d.html?title=view&access_token=pk.eyJ1IjoidWRvYm55aSIsImEiOiJja3liZGU0NzMwZTlhMnBvOHFuOWxlNmYxIn0.mhFm05xmSMi6w28_1fvxVg&zoomwheel=true&fresh=true#9/37.78/-122.4241)
![Screen Shot 2022-06-21 at 17 14 01](https://user-images.githubusercontent.com/5434742/174823817-836bc359-b737-41e6-92cc-714fbab72d24.png)
<img width="1039" alt="Screen Shot 2022-06-21 at 17 13 50" src="https://user-images.githubusercontent.com/5434742/174823919-0b9076f1-289a-4ef9-ae9b-e9468c9b9373.png">

And tried a few options with apple. 
ONE [MAP LINK](https://api.mapbox.com/styles/v1/udobnyi/cl4o60lvk003w14l5qbtopm5a.html?title=view&access_token=pk.eyJ1IjoidWRvYm55aSIsImEiOiJja3liZGU0NzMwZTlhMnBvOHFuOWxlNmYxIn0.mhFm05xmSMi6w28_1fvxVg&zoomwheel=true&fresh=true#9/37.78/-122.4241)
![Screen Shot 2022-06-21 at 16 13 17](https://user-images.githubusercontent.com/5434742/174824420-019d15ba-b568-4012-8cc1-d52ae0bf6ed9.png)
<img width="1080" alt="Screen Shot 2022-06-21 at 15 54 11" src="https://user-images.githubusercontent.com/5434742/174824438-00dc75fe-a7a4-4aca-849b-10555f72fc9f.png">

TWO [MAP LINK](https://api.mapbox.com/styles/v1/udobnyi/cl4o67l33000h16mhfykkki3x.html?title=view&access_token=pk.eyJ1IjoidWRvYm55aSIsImEiOiJja3liZGU0NzMwZTlhMnBvOHFuOWxlNmYxIn0.mhFm05xmSMi6w28_1fvxVg&zoomwheel=true&fresh=true#9/37.78/-122.4241)
![Screen Shot 2022-06-21 at 16 26 04](https://user-images.githubusercontent.com/5434742/174824633-717ebf44-59d7-4686-b136-1eee6ff59c0d.png)
<img width="1038" alt="Screen Shot 2022-06-21 at 16 25 54" src="https://user-images.githubusercontent.com/5434742/174824647-49402fc8-1ed8-4e7f-96c8-2236a0792e41.png">

THREE [MAP LINK](https://api.mapbox.com/styles/v1/udobnyi/cl4o7kagf005314on8p2obyc4.html?title=view&access_token=pk.eyJ1IjoidWRvYm55aSIsImEiOiJja3liZGU0NzMwZTlhMnBvOHFuOWxlNmYxIn0.mhFm05xmSMi6w28_1fvxVg&zoomwheel=true&fresh=true#9/37.78/-122.4241)
![Screen Shot 2022-06-21 at 16 35 32](https://user-images.githubusercontent.com/5434742/174824873-34d968d2-8408-41d0-a004-b2b78ba38294.png)
<img width="1032" alt="Screen Shot 2022-06-21 at 16 35 03" src="https://user-images.githubusercontent.com/5434742/174824889-928f179c-947e-4ee6-9194-26d5c2caa7a8.png">

I really like the second option with an apple (the one with a leaf). It seems to me that the icon with an apple turned out to be a little more cheerful, not so strict. Emotionally she resonates with me

**Comment by Udobnyj** [comment]
We discussed the task with @melanieimfeld and decided to choose an apple w pen, but to try separate them (not to cut off an apple).

[MAP LINK](https://api.mapbox.com/styles/v1/udobnyi/cl4r4usik000m15lkadvxbnwl.html?title=view&access_token=pk.eyJ1IjoidWRvYm55aSIsImEiOiJja3liZGU0NzMwZTlhMnBvOHFuOWxlNmYxIn0.mhFm05xmSMi6w28_1fvxVg&zoomwheel=true&fresh=true#13.17/40.74423/-74.0703)

![Screen Shot 2022-06-23 at 17.45.50.png](https://images.zenhubusercontent.com/61dc302270b3029c9827fc13/cab27d7a-dcae-427d-a7cd-139fde8794b0)
![Screen Shot 2022-06-23 at 17.43.03.png](https://images.zenhubusercontent.com/61dc302270b3029c9827fc13/eb7c480b-efa2-4e52-9f28-0d2962038861)

**Comment by Udobnyj** [comment]
One more approach (I feel like we almost decided)
I've tried to put a pencil in the other direction before, but it didn't work because the apple is firmly planted on the ground.
But @tristen ask me to try to lean it against an apple, and here we go.

It's a bit off the pixel grid. 😞 But raised by 0.5 pixels like this, it looks much better in a circle 
Anyway, what do you think?

[MAP LINK](https://api.mapbox.com/styles/v1/udobnyi/cl4r4usik000m15lkadvxbnwl.html?title=view&access_token=pk.eyJ1IjoidWRvYm55aSIsImEiOiJja3liZGU0NzMwZTlhMnBvOHFuOWxlNmYxIn0.mhFm05xmSMi6w28_1fvxVg&zoomwheel=true&fresh=true#13.17/40.74423/-74.0703)
![Screen Shot 2022-06-23 at 18 56 44](https://user-images.githubusercontent.com/5434742/175342826-30769e09-1e65-4843-a216-4a44f6ab189c.png)
<img width="1106" alt="Screen Shot 2022-06-23 at 18 55 27" src="https://user-images.githubusercontent.com/5434742/175342836-7a2a0613-e2ec-4cdd-9f81-83f14b0bcd7d.png">

**Comment by willymaps** [comment]
@Udobnyj I really like the slightly angled pencil. I wonder if it could still slightly clip the apple to give a 1px separation?

![image](https://user-images.githubusercontent.com/12721145/175397366-b5e7f062-0484-481a-9b80-12a8368ce545.png)

**Comment by melanieimfeld** [comment]
Nice! Agree with @willymaps - the other option would be to try moving the pencil by 1px to the left (if permitted by the layout)

**Comment by Udobnyj** [comment]
SO! I hope this will be our icon 😊
I really love the result. 

[MAP LINK](https://api.mapbox.com/styles/v1/udobnyi/cl4xxqwor000g15s60spq2o3f.html?title=view&access_token=pk.eyJ1IjoidWRvYm55aSIsImEiOiJja3liZGU0NzMwZTlhMnBvOHFuOWxlNmYxIn0.mhFm05xmSMi6w28_1fvxVg&zoomwheel=true&fresh=true/#16.75/40.725289/-74.072223)

<img width="1090" alt="Screen Shot 2022-06-28 at 11 59 24" src="https://user-images.githubusercontent.com/5434742/176139531-c457da63-663d-4516-ab64-386bbaeedb8c.png">

![Screen Shot 2022-06-28 at 11 53 58](https://user-images.githubusercontent.com/5434742/176139587-532dd37f-03a1-463d-8028-eef83bae8aa2.png)

![Screen Shot 2022-06-28 at 11 54 16](https://user-images.githubusercontent.com/5434742/176139596-d651bc64-a9b4-418e-9128-6f38273a89c6.png)

I'm waiting for @willymaps @melanieimfeld @tristen your approval and create a PR
