### ISSUE TITLE
Larger sizes than 11px or 15px (Like 32-40px?)

### ISSUE THREAD

**Issue by domlet** [mapbox/maki#501]
Hey team! Thank you for these icons.

I recently inspected a custom marker available in a GL JS tutorial:

https://docs.mapbox.com/mapbox-gl-js/assets/custom_marker.png

![image](https://user-images.githubusercontent.com/6026447/100918412-49e96e00-348d-11eb-8089-b8bee9abbd28.png)

^ It is 32x40px.

The current Maki icon set offers 11px and 15px icons.

This is how small a 15px icon appears on a map (bottom) compared with the custom marker (top):

![image](https://user-images.githubusercontent.com/6026447/100918587-84530b00-348d-11eb-9726-4f477d81920c.png)

Could we offer another icon size to the map, like 40px, with the intention of making these icons more usable for large, visible custom markers, rather than small, subtle map icons that seem to have an intention of blending into a style without catching anyone's eye?

**Comment by tristen** [comment]
I'm going to close this ticket in favor of an internally referenced one. The next version of Maki icons will only use 15x15 and are drawn as scalable graphics so 30x30 is quite possible. Whatever we do for this, we'll want to run a script that generates them programmatically rather than maintaining larger-sized assets in this project.
