### ISSUE TITLE
Size consistency

### ISSUE THREAD

**Issue by willymaps** [mapbox/maki#555]
### Icon Request

Seeing all of the maki icons together as one single size (15x15) highlights some inconsistencies in the size/stroke widths used.

Proposing we upsize some icons and downsize others where necessary:

### Icons that could be smaller

`aquarium`, `bus`, `caution` (although this is consistent with `roadblock`), `clothing-store`, `post`, `suitcase`

![maki_sm](https://user-images.githubusercontent.com/12721145/123192455-f6626000-d470-11eb-9437-a1e56860459f.png)

### Icons that could be larger

`hot-spring`, `skateboard`, `teahouse`,  `village`

![maki_lg](https://user-images.githubusercontent.com/12721145/123192182-645a5780-d470-11eb-8cb6-43e24804437c.png)

**Comment by Udobnyj** [comment]
I apologize in advance. There will be a lot of icons.

I took the icons that @willymaps  suggested in the description.
After, I checked all the icons for size using blur.
![Screen Shot 2022-05-31 at 18 16 21](https://user-images.githubusercontent.com/5434742/171209018-3d47b4da-e448-4b6b-962e-af140faa4141.png)

After that, I checked them in a circle, singled out those cramped in it, and added some icons from my [alignment task](https://github.com/mapbox/maki/issues/564) to them.
![Screen Shot 2022-05-31 at 18 16 42](https://user-images.githubusercontent.com/5434742/171209322-2a3ecdb0-3fb7-4a7c-adea-4534f0acff54.png)

In the end, I chose 34 icons to change.
![Screen Shot 2022-05-31 at 18 16 49](https://user-images.githubusercontent.com/5434742/171210031-de17504d-378b-475f-9114-63503352b02d.png)

Well, let's get started. I also add a link on the comparing map, but not for all of them. 
Because some, such as "square," are not used.

bus  ![bus](https://user-images.githubusercontent.com/5434742/171212983-4ff60c3f-2237-4c17-9a3c-87c70fe06e99.svg) [MAP LINK](https://hey.mapbox.com/hey-compare-styles/?left=mapbox://styles/udobnyi/cl3u9e0je004q14ny4012ubdq&right=mapbox://styles/udobnyi/cl3u9fass002d15qgl2vif0nd&accessToken=pk.eyJ1IjoidWRvYm55aSIsImEiOiJja3liZGU0NzMwZTlhMnBvOHFuOWxlNmYxIn0.mhFm05xmSMi6w28_1fvxVg#19.07/37.6972724/-122.4856898)
![Screen Shot 2022-05-31 at 15 32 03](https://user-images.githubusercontent.com/5434742/171212855-e54d35d3-eb06-48e4-aec9-b5ab517a50a5.png)
![Screen Shot 2022-05-31 at 15 32 13](https://user-images.githubusercontent.com/5434742/171212877-64050b44-298f-4c5d-9946-cc8646a52ee1.png)

aquarium ![aquarium](https://user-images.githubusercontent.com/5434742/171213367-23c58127-60f0-4f0e-990f-217b787649e9.svg) [MAP LINK](https://hey.mapbox.com/hey-compare-styles/?left=mapbox://styles/udobnyi/cl3u9e0je004q14ny4012ubdq&right=mapbox://styles/udobnyi/cl3u9fass002d15qgl2vif0nd&accessToken=pk.eyJ1IjoidWRvYm55aSIsImEiOiJja3liZGU0NzMwZTlhMnBvOHFuOWxlNmYxIn0.mhFm05xmSMi6w28_1fvxVg#17.53/35.212264/139.009123)
![Screen Shot 2022-05-31 at 15 32 22](https://user-images.githubusercontent.com/5434742/171213450-c898401a-215f-438d-a9c8-58c3b0f66084.png)
![Screen Shot 2022-05-31 at 15 32 30](https://user-images.githubusercontent.com/5434742/171213469-7d0da187-decf-4d51-89e4-b4b0be25f6c4.png)

clothing-store ![clothing-store](https://user-images.githubusercontent.com/5434742/171213974-361a1096-b63e-43cc-8ee3-ae048d6bb5a1.svg) [MAP LINK](https://hey.mapbox.com/hey-compare-styles/?left=mapbox://styles/udobnyi/cl3u9e0je004q14ny4012ubdq&right=mapbox://styles/udobnyi/cl3u9fass002d15qgl2vif0nd&accessToken=pk.eyJ1IjoidWRvYm55aSIsImEiOiJja3liZGU0NzMwZTlhMnBvOHFuOWxlNmYxIn0.mhFm05xmSMi6w28_1fvxVg#19.02/32.0551877/34.7665053)
![Screen Shot 2022-05-31 at 15 32 45](https://user-images.githubusercontent.com/5434742/171214071-cce7b836-fde6-480b-b0e8-1c6b8c160348.png)
![Screen Shot 2022-05-31 at 15 32 53](https://user-images.githubusercontent.com/5434742/171214085-476d2a76-964b-4308-8c0b-32e9842a2f06.png)

post ![post](https://user-images.githubusercontent.com/5434742/171214209-d77d790a-d611-47d7-badd-865ae2b18f50.svg) [MAP LINK](https://hey.mapbox.com/hey-compare-styles/?left=mapbox://styles/udobnyi/cl3u9e0je004q14ny4012ubdq&right=mapbox://styles/udobnyi/cl3u9fass002d15qgl2vif0nd&accessToken=pk.eyJ1IjoidWRvYm55aSIsImEiOiJja3liZGU0NzMwZTlhMnBvOHFuOWxlNmYxIn0.mhFm05xmSMi6w28_1fvxVg#18.84/55.778927/37.5563962)
![Screen Shot 2022-05-31 at 15 33 02](https://user-images.githubusercontent.com/5434742/171214271-25e12479-40b9-43f2-bb1b-393803424195.png)
![Screen Shot 2022-05-31 at 15 33 14](https://user-images.githubusercontent.com/5434742/171214296-c861a35b-a16c-44f8-bb2d-e30efe8fe048.png)

religious-jewish ![religious-jewish](https://user-images.githubusercontent.com/5434742/171214377-697f9335-c393-48ef-ac92-2bb1d2ff1b89.svg) [MAP LINK](https://hey.mapbox.com/hey-compare-styles/?left=mapbox://styles/udobnyi/cl3u9e0je004q14ny4012ubdq&right=mapbox://styles/udobnyi/cl3u9fass002d15qgl2vif0nd&accessToken=pk.eyJ1IjoidWRvYm55aSIsImEiOiJja3liZGU0NzMwZTlhMnBvOHFuOWxlNmYxIn0.mhFm05xmSMi6w28_1fvxVg#17.86/32.027536/34.772668)
![Screen Shot 2022-05-31 at 15 33 23](https://user-images.githubusercontent.com/5434742/171214455-dcbb4540-80a6-4b92-babc-f80c0229f0e1.png)
![Screen Shot 2022-05-31 at 15 33 34](https://user-images.githubusercontent.com/5434742/171214464-fdd0f034-5bda-456c-b0ea-affebc1d638b.png)

square ![square](https://user-images.githubusercontent.com/5434742/171214511-1eda1a9a-adb1-4bd0-8fe9-4a9d2cc5c1d2.svg)
![Screen Shot 2022-05-31 at 15 33 44](https://user-images.githubusercontent.com/5434742/171214534-648b7fde-6dbc-42f1-a538-c8a469c26cd8.png)
![Screen Shot 2022-05-31 at 15 33 52](https://user-images.githubusercontent.com/5434742/171214550-0bb35635-a0f7-48c1-9ec7-11739f2e16b7.png)

square-stroked ![square-stroked](https://user-images.githubusercontent.com/5434742/171214607-878f91e4-7b77-459b-948e-80be9d49772b.svg)
![Screen Shot 2022-05-31 at 15 34 00](https://user-images.githubusercontent.com/5434742/171214660-47173b18-94b8-401c-af96-7ef03f292a26.png)
![Screen Shot 2022-05-31 at 15 34 08](https://user-images.githubusercontent.com/5434742/171214680-96a5b066-18dd-4257-bc0f-7dae4f3c768e.png)

marker-stroked ![marker-stroked](https://user-images.githubusercontent.com/5434742/171214782-a4310575-dba9-4522-80d0-24f505e497d0.svg)
![Screen Shot 2022-05-31 at 15 34 16](https://user-images.githubusercontent.com/5434742/171214812-b6bd6f9e-c54d-4deb-aee5-562ce3f5721c.png)
![Screen Shot 2022-05-31 at 15 34 27](https://user-images.githubusercontent.com/5434742/171214833-d659a59b-7618-4f81-932a-df9513d71dc3.png)

marker ![marker](https://user-images.githubusercontent.com/5434742/171214875-aa906088-4157-4330-a091-d5ed20de9c1a.svg)
![Screen Shot 2022-05-31 at 15 34 34](https://user-images.githubusercontent.com/5434742/171214927-3f78216b-16b0-4c81-bdbe-8fe4be6d21b1.png)
![Screen Shot 2022-05-31 at 15 34 43](https://user-images.githubusercontent.com/5434742/171214945-b99c2996-ce0d-468a-805b-4a25b3533673.png)

circle-stroked ![circle-stroked](https://user-images.githubusercontent.com/5434742/171215087-7ccf669a-7edf-45b8-a235-12e5b9436beb.svg)
![Screen Shot 2022-05-31 at 15 34 51](https://user-images.githubusercontent.com/5434742/171215114-343f1c45-770e-496e-8a20-080c4ba1132d.png)
![Screen Shot 2022-05-31 at 15 35 05](https://user-images.githubusercontent.com/5434742/171215133-8fec42fa-b8d4-4e5b-acf2-62166b543914.png)

fire-station ![fire-station](https://user-images.githubusercontent.com/5434742/171215227-6f1dbefd-79eb-4674-be10-a8d3297470a2.svg) [MAP LINK](https://hey.mapbox.com/hey-compare-styles/?left=mapbox://styles/udobnyi/cl3u9e0je004q14ny4012ubdq&right=mapbox://styles/udobnyi/cl3u9fass002d15qgl2vif0nd&accessToken=pk.eyJ1IjoidWRvYm55aSIsImEiOiJja3liZGU0NzMwZTlhMnBvOHFuOWxlNmYxIn0.mhFm05xmSMi6w28_1fvxVg#16.66/35.249108/138.851373)
![Screen Shot 2022-05-31 at 15 35 15](https://user-images.githubusercontent.com/5434742/171215333-a1286e8f-b8a6-4777-82b4-5e6ab6049643.png)
![Screen Shot 2022-05-31 at 15 35 26](https://user-images.githubusercontent.com/5434742/171215347-5ee16f3d-bb33-4cef-9409-60c5625b8b0d.png)

roadblock ![roadblock](https://user-images.githubusercontent.com/5434742/171215551-e516dfdb-af50-49e4-8bd6-ef2215732466.svg)
![Screen Shot 2022-05-31 at 15 35 35](https://user-images.githubusercontent.com/5434742/171215572-0e576f05-1266-4b7f-a759-5fa6da919609.png)
![Screen Shot 2022-05-31 at 15 35 42](https://user-images.githubusercontent.com/5434742/171215592-36e9a9f8-b7ac-44f5-bcb7-7a5aeebc9a0b.png)

caution ![caution](https://user-images.githubusercontent.com/5434742/171215718-0fb12733-ee74-45bc-a408-c63a5530f60b.svg)
![Screen Shot 2022-05-31 at 15 35 51](https://user-images.githubusercontent.com/5434742/171215757-d1250ac2-cf52-4122-bcbf-7c82cbee108b.png)
![Screen Shot 2022-05-31 at 15 36 00](https://user-images.githubusercontent.com/5434742/171215795-c178a35a-1dcf-4fd3-a055-b3309059391d.png)

suitcase ![suitcase](https://user-images.githubusercontent.com/5434742/171215994-5a365153-f4b3-4288-8cb5-e5da738bab60.svg)
![Screen Shot 2022-05-31 at 15 36 08](https://user-images.githubusercontent.com/5434742/171216022-f2698c2a-4356-42db-a5e0-75400af1ee20.png)
![Screen Shot 2022-05-31 at 15 36 17](https://user-images.githubusercontent.com/5434742/171216034-7d9061ac-4d3b-4e3d-9f33-d91019c17c7c.png)

campsite ![campsite](https://user-images.githubusercontent.com/5434742/171216100-7bf8773a-e4e1-4f60-8370-1377fae81d12.svg) [MAP LINK](https://hey.mapbox.com/hey-compare-styles/?left=mapbox://styles/udobnyi/cl3u9e0je004q14ny4012ubdq&right=mapbox://styles/udobnyi/cl3u9fass002d15qgl2vif0nd&accessToken=pk.eyJ1IjoidWRvYm55aSIsImEiOiJja3liZGU0NzMwZTlhMnBvOHFuOWxlNmYxIn0.mhFm05xmSMi6w28_1fvxVg#17.93/29.498171/34.912549)
![Screen Shot 2022-05-31 at 15 36 25](https://user-images.githubusercontent.com/5434742/171216160-23db17b7-7715-4677-889d-0965acd33ccc.png)
![Screen Shot 2022-05-31 at 15 37 11](https://user-images.githubusercontent.com/5434742/171216178-86180c70-2346-41ad-bd7b-054bdad79335.png)

water ![water](https://user-images.githubusercontent.com/5434742/171216232-28b343ce-a43a-4301-bf12-9489bb8a2760.svg)
![Screen Shot 2022-05-31 at 15 37 21](https://user-images.githubusercontent.com/5434742/171216251-b5d40fdd-1cca-490d-a9ab-6169fd42187b.png)
![Screen Shot 2022-05-31 at 15 37 32](https://user-images.githubusercontent.com/5434742/171216263-baf62dda-f66e-459e-8322-544c87534fd4.png)

gift ![gift](https://user-images.githubusercontent.com/5434742/171216397-6c913312-eaf1-40df-a1c9-65adca1a48d9.svg)
![Screen Shot 2022-05-31 at 15 37 43](https://user-images.githubusercontent.com/5434742/171216424-712f6f67-d260-4712-aeb7-9a589a807f9a.png)
![Screen Shot 2022-05-31 at 15 37 52](https://user-images.githubusercontent.com/5434742/171216446-9f2c8462-8cb0-4b6d-8402-75d5585f9c23.png)

waterfall ![waterfall](https://user-images.githubusercontent.com/5434742/171216507-2e314f2f-14ce-433a-a226-3291c0961734.svg)
![Screen Shot 2022-05-31 at 15 38 00](https://user-images.githubusercontent.com/5434742/171216530-17f4a385-1cc8-44e5-9cce-3f3803ba862e.png)
![Screen Shot 2022-05-31 at 15 38 06](https://user-images.githubusercontent.com/5434742/171216545-e615eb26-b9eb-4404-bd12-7f6cb8026901.png)

toilet ![toilet](https://user-images.githubusercontent.com/5434742/171216666-402ab96f-98d6-4a96-b25f-19c6b22998c7.svg) [MAP LINK](https://hey.mapbox.com/hey-compare-styles/?left=mapbox://styles/udobnyi/cl3u9e0je004q14ny4012ubdq&right=mapbox://styles/udobnyi/cl3u9fass002d15qgl2vif0nd&accessToken=pk.eyJ1IjoidWRvYm55aSIsImEiOiJja3liZGU0NzMwZTlhMnBvOHFuOWxlNmYxIn0.mhFm05xmSMi6w28_1fvxVg#20.11/31.7768918/35.2336398)
![Screen Shot 2022-05-31 at 15 38 15](https://user-images.githubusercontent.com/5434742/171216730-715f80d1-b2ae-48b2-a59e-3da7a955338a.png)
![Screen Shot 2022-05-31 at 15 38 23](https://user-images.githubusercontent.com/5434742/171216741-58f9570f-a6d3-4e64-9bc0-5fc515814122.png)

city ![city](https://user-images.githubusercontent.com/5434742/171216897-5c8551c2-7949-4438-998d-2ab68c172a3b.svg) 
![Screen Shot 2022-05-31 at 15 38 31](https://user-images.githubusercontent.com/5434742/171216923-7376d9fa-6c9c-41d9-a14f-234471f21888.png)
![Screen Shot 2022-05-31 at 15 38 38](https://user-images.githubusercontent.com/5434742/171216940-18bda0dc-87c0-45b3-9bbd-b4279db774f6.png)

cross ![cross](https://user-images.githubusercontent.com/5434742/171216971-e682d097-e90e-4301-8fbb-e57cee35776d.svg)
![Screen Shot 2022-05-31 at 15 38 46](https://user-images.githubusercontent.com/5434742/171216992-bf28acf5-03d9-4941-a914-cf1bf0968af1.png)
![Screen Shot 2022-05-31 at 15 38 56](https://user-images.githubusercontent.com/5434742/171217008-11f6b449-5e01-423a-b5a1-e37770f92023.png)

car-rental ![car-rental](https://user-images.githubusercontent.com/5434742/171217066-b5cfc5cb-0f55-4383-8d85-2abed7a8e097.svg) [MAP LINK](https://hey.mapbox.com/hey-compare-styles/?left=mapbox://styles/udobnyi/cl3u9e0je004q14ny4012ubdq&right=mapbox://styles/udobnyi/cl3u9fass002d15qgl2vif0nd&accessToken=pk.eyJ1IjoidWRvYm55aSIsImEiOiJja3liZGU0NzMwZTlhMnBvOHFuOWxlNmYxIn0.mhFm05xmSMi6w28_1fvxVg#20.34/37.7684065/-122.4109369)
![Screen Shot 2022-05-31 at 15 39 06](https://user-images.githubusercontent.com/5434742/171217284-fe436b9f-c61a-4211-a3b6-c89d4b3f474a.png)
![Screen Shot 2022-05-31 at 15 39 21](https://user-images.githubusercontent.com/5434742/171217295-86126bea-3edc-475c-b4a7-3966a9539fea.png)

car-repair ![car-repair](https://user-images.githubusercontent.com/5434742/171217325-62aca669-c24c-42b9-8125-ab5144f4bf1e.svg) [MAP LINK](https://hey.mapbox.com/hey-compare-styles/?left=mapbox://styles/udobnyi/cl3u9e0je004q14ny4012ubdq&right=mapbox://styles/udobnyi/cl3u9fass002d15qgl2vif0nd&accessToken=pk.eyJ1IjoidWRvYm55aSIsImEiOiJja3liZGU0NzMwZTlhMnBvOHFuOWxlNmYxIn0.mhFm05xmSMi6w28_1fvxVg#19.37/37.7727609/-122.4124666)
![Screen Shot 2022-05-31 at 15 39 31](https://user-images.githubusercontent.com/5434742/171217395-135f9672-d589-4011-91b2-709a6bbc9352.png)
![Screen Shot 2022-05-31 at 15 39 41](https://user-images.githubusercontent.com/5434742/171217417-019917ed-bd11-4b94-bc35-fd1cefb73f36.png)

religious-muslim ![religious-muslim](https://user-images.githubusercontent.com/5434742/171217451-7bb36e68-2cd5-4844-b110-594461c890bf.svg)
![Screen Shot 2022-05-31 at 15 39 48](https://user-images.githubusercontent.com/5434742/171217492-18d786c7-d049-484b-bfd1-0fdeaa48c624.png)
![Screen Shot 2022-05-31 at 15 39 56](https://user-images.githubusercontent.com/5434742/171217513-c79858ca-64d6-41ab-aec0-9490f759ea61.png)

bowling-alley ![bowling-alley](https://user-images.githubusercontent.com/5434742/171217575-2400b938-e87a-4076-9e9c-40fa8eda226a.svg)
![Screen Shot 2022-05-31 at 15 40 23](https://user-images.githubusercontent.com/5434742/171217603-28de1c99-5dba-4183-bbae-2203a5dfa8ae.png)
![Screen Shot 2022-05-31 at 15 40 31](https://user-images.githubusercontent.com/5434742/171217697-3ddc5318-f630-4bdf-a72d-1ca29c78c77a.png)

amusement-park ![amusement-park](https://user-images.githubusercontent.com/5434742/171217743-0fc8d923-0793-45e5-8faf-00abf2018d64.svg) [MAP LINK](https://hey.mapbox.com/hey-compare-styles/?left=mapbox://styles/udobnyi/cl3u9e0je004q14ny4012ubdq&right=mapbox://styles/udobnyi/cl3u9fass002d15qgl2vif0nd&accessToken=pk.eyJ1IjoidWRvYm55aSIsImEiOiJja3liZGU0NzMwZTlhMnBvOHFuOWxlNmYxIn0.mhFm05xmSMi6w28_1fvxVg#17.91/35.294255/138.783796)
![Screen Shot 2022-05-31 at 15 40 39](https://user-images.githubusercontent.com/5434742/171217815-e54f6374-11a0-477c-9933-4e991d4f3a26.png)
![Screen Shot 2022-05-31 at 15 40 46](https://user-images.githubusercontent.com/5434742/171217838-711a226f-4cbb-4c3a-bb51-a51e633d22c0.png)

shelter ![shelter](https://user-images.githubusercontent.com/5434742/171217900-0cc203b5-c75a-4e42-a3e1-689bb75a252e.svg)
![Screen Shot 2022-05-31 at 15 40 56](https://user-images.githubusercontent.com/5434742/171217933-f4a6a23b-44f1-4465-be55-3fc2ab767cd0.png)
![Screen Shot 2022-05-31 at 15 41 03](https://user-images.githubusercontent.com/5434742/171217942-8024384e-1a93-4226-b5bc-753609e3b955.png)

basketball ![basketball](https://user-images.githubusercontent.com/5434742/171217998-7c460795-ea31-4338-8928-ed9e7495c374.svg) [MAP LINK](https://hey.mapbox.com/hey-compare-styles/?left=mapbox://styles/udobnyi/cl3u9e0je004q14ny4012ubdq&right=mapbox://styles/udobnyi/cl3u9fass002d15qgl2vif0nd&accessToken=pk.eyJ1IjoidWRvYm55aSIsImEiOiJja3liZGU0NzMwZTlhMnBvOHFuOWxlNmYxIn0.mhFm05xmSMi6w28_1fvxVg#19.83/29.5136482/34.9254717)
![Screen Shot 2022-05-31 at 15 41 14](https://user-images.githubusercontent.com/5434742/171218073-e5f52e63-c824-4fcc-8ce6-48104d90ab82.png)
![Screen Shot 2022-05-31 at 15 41 21](https://user-images.githubusercontent.com/5434742/171218085-e4f3db54-12e2-436b-b09d-9251b89c6aac.png)

ferry-JP ![ferry-JP](https://user-images.githubusercontent.com/5434742/171218138-9a4583ac-ab69-4184-899c-cb86e8a5cf01.svg)
![Screen Shot 2022-05-31 at 15 41 29](https://user-images.githubusercontent.com/5434742/171218155-661ebca4-33b3-46d0-9fd6-68882a2afb76.png)
![Screen Shot 2022-05-31 at 15 41 37](https://user-images.githubusercontent.com/5434742/171218164-9ae809b7-678e-4575-a319-fe6ed9618660.png)

**Comment by Udobnyj** [comment]
We discussed and decided to open a PR for this task. it will be easier to compare the changes in that way.
