### ISSUE TITLE
`gate` and `lift_gate` icons

### ISSUE THREAD

**Issue by tayalav** [mapbox/maki#563]
### Icon Request
Add `gate` and `lift_gate` icons

Initial thoughts:
- `gate` icon intended to indicate a section in a [wall](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dwall) or [fence](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dfence) which can be opened to allow or restrict access.
-  `lift_gate` icon intended to indicate a bar, or pole pivoted (rotates upwards to open) in such a way as to allow the boom to block vehicular access through a controlled point. 

OSM tag: https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dgate
OSM tag: https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dlift_gate

**Comment by willymaps** [comment]
@tayalav just looking at existing icons, could https://github.com/mapbox/maki/blob/main/icons/fence.svg work for `gate`?

I imagine `lift_gate` will be similar to https://github.com/mapbox/maki/blob/main/icons/toll-booth.svg, but likely doesn't need the physical structure beside the gate.

**Comment by Udobnyj** [comment]
I changed a bit lift_gate because it didn't work on mao well.
![Screen Shot 2022-05-17 at 20.27.12.png](https://images.zenhubusercontent.com/61dc302270b3029c9827fc13/5a3fb063-7f46-49e5-8ed5-fcb6eff114c7)

[Map link to check](https://api.mapbox.com/styles/v1/udobnyi/cl3aeujfb000615p5ejx9hu5o.html?title=view&access_token=pk.eyJ1IjoidWRvYm55aSIsImEiOiJja3liZGU0NzMwZTlhMnBvOHFuOWxlNmYxIn0.mhFm05xmSMi6w28_1fvxVg&zoomwheel=true&fresh=true#19.2/37.7700716/-122.4394469)
![Screen Shot 2022-05-17 at 20.27.03.png](https://images.zenhubusercontent.com/61dc302270b3029c9827fc13/cb0bd7db-b533-4b7f-b051-ea962d98ffc0)

SVGs and [Figma link](https://www.figma.com/file/sW5W8xFa7RzsbgU6JTNwwJ/Maki-WIP?node-id=503%3A773)
![lift_gate.svg](https://images.zenhubusercontent.com/61dc302270b3029c9827fc13/c1a43675-41a6-4b00-bb01-586a535ee3c8) ![gate.svg](https://images.zenhubusercontent.com/61dc302270b3029c9827fc13/edf02089-8a20-47d2-86e3-fdeaa626624d)

**Comment by Udobnyj** [comment]
@tayalav Hey! Let's close this one and move all the work to this one. Ok?
https://app.zenhub.com/workspaces/map-design-team-5ed96b144161fad651898382/issues/mapbox/mapbox-core-style-icons/237

**Comment by Udobnyj** [comment]
[Let's continue working here](https://app.zenhub.com/workspaces/map-design-team-5ed96b144161fad651898382/issues/mapbox/mapbox-core-style-icons/237)
