### ISSUE TITLE
Center icons

### ISSUE THREAD

**Issue by willymaps** [mapbox/maki#564]
#### Icon Request

When placing maki icons inside of a background shape, icons that aren't centered vertically/horizontally appear too close to the background shape padding.

![image](https://user-images.githubusercontent.com/12721145/164251701-554bb034-9654-4b19-b4f9-b6e60ba3e89c.png)

Icons that stand out are `skiing`, `village`, `barrier`, `fence`, and `bridge`.

**Comment by willymaps** [comment]
`slaughterhouse` is likely the most problematic and has been discussed [1](https://github.com/mapbox/maki/issues/396), [2](https://github.com/mapbox/maki/issues/542)

**Comment by Udobnyj** [comment]
I checked all of the Maki icons. And choose 46 to change.

![Screen Shot 2022-04-26 at 13 45 43](https://user-images.githubusercontent.com/5434742/165283513-979944b4-51f4-4a4d-92ca-3ad6ac862d5f.png)

I moved them inside their 15px artboards. There is a changing comparing gif.
![maki centered](https://user-images.githubusercontent.com/5434742/165283688-3adcd1ac-1e7a-412d-b086-99b050e14516.gif)

Сheck please all my changes in the Figma file
https://www.figma.com/file/Ogqi7HpbVlr8yGw3ZrYL3g/Maki?node-id=319%3A1012

For six of them, I moved not accurate 1 pixel. but 0.5 pixel 
I know we are trying to keep them in the grid, but TBH, many of them are already not so hard connected to the pixel grid. Maybe we can skip it? What do you think? Because they are looking way better moved that way.

![Screen Shot 2022-04-26 at 14 02 13](https://user-images.githubusercontent.com/5434742/165286654-8385194f-8b66-46c6-8368-8c37814ad507.png)

And I have one more creepy one with no ability to move it because it filled the whole artboard.
![Screen Shot 2022-04-26 at 13 45 50](https://user-images.githubusercontent.com/5434742/165288428-82033421-3e90-480b-9e52-874bac68a142.png)
