### ISSUE TITLE
icon for slipway / boat launch

### ISSUE THREAD

**Issue by ansis** [mapbox/maki#58]
something like http://thenounproject.com/noun/boat-launch/#icon-No200

**Comment by natslaughter** [comment]
going with a motorboat on ramp for the symbol concept

<img width="390" alt="screen shot 2018-05-10 at 10 20 53 am" src="https://user-images.githubusercontent.com/16616543/39874887-12d90110-543d-11e8-9169-07bf70ae675d.png">

**next steps**
- [ ] icon design refinement
- [ ] test icon on maps
- [ ] geometric cleaning & svg file preparation

**Comment by rasagy** [comment]
The motorboat icon in the initial concept was not very legible, especially at the 11px version. I played with a few alternatives, from trying to add a pump/engine and a wind shield to going with the old style of a boat sail.

<img width="271" alt="screenshot 2018-06-25 19 05 28 - options" src="https://user-images.githubusercontent.com/1117531/41854207-44b226aa-78ad-11e8-91a6-4a9ae0fad656.png">

Here are two versions that I narrowed down on:

<img width="35" alt="screenshot 2018-06-25 19 05 28" src="https://user-images.githubusercontent.com/1117531/41854334-a09d9fda-78ad-11e8-8931-8a839f117a47.png">

<img width="37" alt="screenshot 2018-06-25 17 48 28" src="https://user-images.githubusercontent.com/1117531/41854433-de60173a-78ad-11e8-8201-6d5e762ebe64.png">

**Comment by natslaughter** [comment]
@rasagy I like the direction of the last three schemes here: the first two are comprised of boat types that generally do not use slipways, and are stored always in the water. 

I'm not boat expert, but if you do an image search online for `motorboat`, `fishing boat` or even `row boat`, you can find some examples. 

I think the critical thing here is to develop the two elements of the boat silhouette - the windshield and motor tail - so that the boat shape is unique and distinguishable. 

I would consider exploring:
- making the slipway less prominent, maybe thinner, especially on the 11 pixel icon
- developing and refining the windshield and tail elements. perhaps looking at some boat images online will assist here.

**Comment by rasagy** [comment]
I worked on reducing the emphasis on the slipway, and adding more weight to the silhouette of the boat. Here’s the iteration:

8x:
<img width="268" alt="screenshot 2018-07-17 18 43 14" src="https://user-images.githubusercontent.com/1117531/42819502-6615c522-89f1-11e8-9295-8d92094d8a65.png">

1x:
<img width="38" alt="screenshot 2018-07-17 18 43 00" src="https://user-images.githubusercontent.com/1117531/42819509-6cd38548-89f1-11e8-8409-1fedee30ec3a.png">

@natslaughter Thoughts on removing the negative space in 11px icon, and how I’m simplifying the tail?

**Comment by natslaughter** [comment]
seems like adding a trailer platform with a wheel would help distinguish it from a plane, in addition to be similar to existing takes on the slipway icon

![image](https://user-images.githubusercontent.com/16616543/42892273-6ef1a538-8a7f-11e8-9ea3-ef7bc4971c88.png)

![image](https://user-images.githubusercontent.com/16616543/42892285-76546f72-8a7f-11e8-90e2-5d9555b9c4fa.png)

**Comment by tristen** [comment]
This exists https://github.com/mapbox/maki/blob/master/icons/slipway-15.svg
